bitbucket:
  api:
    email: ${BITBUCKET_EMAIL:}
    token: ${BITBUCKET_API_TOKEN:}
    workspace: ${BITBUCKET_WORKSPACE:}

quarkus:
  rest-client:
    bitbucket-api:
      url: https://api.bitbucket.org/2.0
      scope: jakarta.enterprise.context.ApplicationScoped
      follow-redirects: true
  log:
    category:
      "org.jboss.resteasy.reactive.client":
        level: DEBUG
      "com.subrutin.bitbucket":
        level: DEBUG

# Profile untuk HTTPS
# "%https":
#   quarkus:
#     http:
#       ssl:
#         certificate:
#           key-store-file: src/main/resources/keystore.p12
#           key-store-password: ${SSL_KEYSTORE_PASSWORD:password}
#       ssl-port: 8443
#       insecure-requests: redirect
